# Generated by Django 4.1.3 on 2022-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
